# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

# Variables
variables:
  tag: '($Build.BuildId)'

stages:
#Buiild Stage
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: Build Job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'docker_registry'
        repository: 'azure-devops-exporter'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          #$(tag)
          $(Build.SourceVersion)