#version: '3.7'

volumes:
  grafana_data: {}

services:
 prometheus:
   image: prom/prometheus
   ports:
     - "9090:9090"
   volumes:
     - ./prometheus/config:/etc/prometheus/
     - ./prometheus/data:/prometheus
     #- /etc/localtime:/etc/localtime:ro
     #- /etc/timezone:/etc/timezone:ro
   command:
     - '--config.file=/etc/prometheus/prometheus.yml'
     - '--storage.tsdb.path=/prometheus'
     - '--web.console.templates=/etc/prometheus/consoles'
     - '--web.console.libraries=/etc/prometheus/console_libraries'

 azure-exporter:
   build: .
   ports:
     - "8080:8080"
   environment:
     #- AZURE_DEVOPS_URL=https://azdo-pdpt.corp.itsroot.biz
     #- AZURE_DEVOPS_ACCESS_TOKEN=t3gm5t4tcm3xj7su2itxhtpgmtov6zxszzyfqbyiuu56bygzuzma
     - AZURE_DEVOPS_URL=https://azdo.corp.itsroot.biz
     - AZURE_DEVOPS_ACCESS_TOKEN=mnd3c7rqhlz4dymbtkg5inbe6hpg4rompqp5bh77nhmstvhf6wbq
     - AZURE_DEVOPS_ORGANISATION=ypsomed
     #- AZURE_DEVOPS_FILTER_AGENTPOOL=2
    #  - AZURE_DEVOPS_FILTER_AGENTPOOL=5
    #  - AZURE_DEVOPS_FILTER_AGENTPOOL=3
    #  - LIMIT_BUILD_HISTORY_DURATION=1000000h
    #  - LIMIT_RELEASE_HISTORY_DURATION=1000000h
    #  - LIMIT_PROJECT=10000
    #  - LIMIT_BUILDS_PER_PROJECT=100000
    #  - LIMIT_BUILDS_PER_DEFINITION=100000
    #  - LIMIT_RELEASES_PER_PROJECT=100000
    #  - LIMIT_RELEASES_PER_DEFINITION=100000
    #  - LIMIT_DEPLOYMENTS_PER_DEFINITION=100000
    #  - LIMIT_RELEASEDEFINITION_PER_PROJECT=100000
    #  - STATS_SUMMARY_MAX_AGE=1000000h
    #  - SCRAPE_TIME=1m
    #  - SCRAPE_TIME_LIVE=5s
   depends_on:
     - prometheus

 grafana:
   image: grafana/grafana
   # optional - just a test from a tutorial
   #environment:
    #GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
   ports:
     - "3000:3000"
   volumes:
     #- /etc/localtime:/etc/localtime:ro
     #- /etc/timezone:/etc/timezone:ro
     - grafana_data:/var/lib/grafana
     - ./grafana/provisioning/:/etc/grafana/provisioning/
   env_file:
     - ./grafana/config.monitoring
   depends_on:
     - azure-exporter

