# Docker
# Build and Push a Docker image

trigger:
  branches:
    include:
    - pre-release

resources:
- repo: self

# Variables
variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'docker_registry'
  imageRepository: 'michaelerb/azure-devops-exporter_off-prem'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'docker-reg'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: Build Job
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Login to docker registry
      inputs:
        containerRegistry: 'docker_registry'
        command: 'login'    
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: 'buildAndPush'
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        Dockerfile: $(dockerfilePath)
        tags: |
          $(Build.SourceVersion) 

    - upload: manifests
      artifact: manifests


# ## Publish Artifacts pipeline code in addition to Build and Push          
#     - bash: echo Contents in System Default Working Directory; ls -R $(System.DefaultWorkingDirectory)        
#     - bash: echo Before copying Contents in Build Artifact Directory; ls -R $(Build.ArtifactStagingDirectory)        
#     # Task-2: Copy files (Copy files from a source folder to target folder)
#     # Source Directory: $(System.DefaultWorkingDirectory)/kube-manifests
#     # Target Directory: $(Build.ArtifactStagingDirectory)
#     - task: CopyFiles@2
#       inputs:
#         SourceFolder: '$(System.DefaultWorkingDirectory)/manifests'
#         Contents: '**'
#         TargetFolder: '$(Build.ArtifactStagingDirectory)'
#         OverWrite: true
#     # List files from Build Artifact Staging Directory - After Copy
#     - bash: echo After copying to Build Artifact Directory; ls -R $(Build.ArtifactStagingDirectory)  
#     # Task-3: Publish build artifacts (Publish build to Azure Pipelines)

    # - task: KubernetesManifest@0
    #   inputs:
    #     action: 'deploy'
    #     kubernetesServiceConnection: 'aks_monitoring'
    #     namespace: 'do'
    #     manifests: '$(Pipeline.Workspace)/manifests/azure-devops-exporter.yaml'


# Kubernetes
# Deploy to cluster

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: do
    strategy:
      runOnce:
        deploy:
          steps:
          # - task: KubernetesManifest@0
          #   displayName: Create imagePullSecret
          #   inputs:
          #     action: createSecret
          #     secretName: $(imagePullSecret)
          #     dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

          # - task: KubernetesManifest@0
          #   displayName: Deploy to Kubernetes cluster
          #   inputs:
          #     kubernetesServiceConnection: aks_monitoring
          #     #kubernetesServiceConnection: aks_serviceconnection
          #     action: deploy
          #     manifests: |
          #       $(Pipeline.Workspace)/manifests/azure-exporter-deployment.yaml
          #     containers: |
          #       michaelerb/azure-devops-exporter_azure-exporter

          # - task: KubernetesManifest@0
          #   displayName: Create imagePullSecret
          #   inputs:
          #     action: createSecret
          #     secretName: $(imagePullSecret)
          #     kubernetesServiceConnection: aks_monitoring
          #     namespace: do
          #     dockerRegistryEndpoint: docker_registry
              
          # - task: KubernetesManifest@0
          #   displayName: Deploy to Kubernetes cluster
          #   inputs:
          #     action: deploy
          #     namespace: do
          #     manifests: |
          #       $(System.ArtifactsDirectory)/manifests/azure-exporter-deployment.yaml
          #     imagePullSecrets: |
          #       $(imagePullSecret)
          #     containers: |
          #       michaelerb/azure-devops-exporter_off-prem


          # - task: KubernetesManifest@0
          #   displayName: Create imagePullSecret
          #   inputs:
          #     action: createSecret
          #     secretName: $(imagePullSecret)
          #     dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              kubernetesServiceConnection: aks_test2
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/manifests/azure-exporter-deployment.yaml
              containers: |
                michaelerb/azure-devops-exporter_off-prem:0.1