{
 "title": "devops-monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "buildname",
    "query": "azure_devops_build_definition_info"
   }
  ]
 },
 "panels": [
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2.4, "x": 0, "y": 0 },
   "repeat": "buildname",
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "azure_devops_build_latest_info{buildName=\"$buildname\"}",
     "legendFormat": "{{buildNumber}}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2.4, "x": 2.4, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "azure_devops_build_latest_info{buildName=\"$buildname\"}",
     "legendFormat": "{{buildNumber}}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2.4, "x": 4.8, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "azure_devops_build_latest_info{buildName=\"$buildname\"}",
     "legendFormat": "{{buildNumber}}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2.4, "x": 7.199999999999999, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "azure_devops_build_latest_info{buildName=\"$buildname\"}",
     "legendFormat": "{{buildNumber}}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2.4, "x": 9.6, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "azure_devops_build_latest_info{buildName=\"$buildname\"}",
     "legendFormat": "{{buildNumber}}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2.4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "azure_devops_build_latest_info{buildName=\"$buildname\"}",
     "legendFormat": "{{buildNumber}}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2.4, "x": 14.4, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "azure_devops_build_latest_info{buildName=\"$buildname\"}",
     "legendFormat": "{{buildNumber}}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2.4, "x": 16.8, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "azure_devops_build_latest_info{buildName=\"$buildname\"}",
     "legendFormat": "{{buildNumber}}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2.4, "x": 19.2, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "azure_devops_build_latest_info{buildName=\"$buildname\"}",
     "legendFormat": "{{buildNumber}}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2.4, "x": 21.599999999999998, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "azure_devops_build_latest_info{buildName=\"$buildname\"}",
     "legendFormat": "{{buildNumber}}"
    }
   ]
  },
  {
   "title": "$buildname",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2.4, "x": 0, "y": 2 },
   "repeat": "buildname",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(azure_devops_build_latest_info{result=\"succeeded\", buildName=\"$buildname\"} / azure_devops_build_latest_info{buildName=\"$buildname\"}) by (buildName, buildNumber)",
     "legendFormat": "{{buildName}} {{buildNumber}}"
    }
   ]
  },
  {
   "title": "$buildname",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2.4, "x": 2.4, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(azure_devops_build_latest_info{result=\"succeeded\", buildName=\"$buildname\"} / azure_devops_build_latest_info{buildName=\"$buildname\"}) by (buildName, buildNumber)",
     "legendFormat": "{{buildName}} {{buildNumber}}"
    }
   ]
  },
  {
   "title": "$buildname",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2.4, "x": 4.8, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(azure_devops_build_latest_info{result=\"succeeded\", buildName=\"$buildname\"} / azure_devops_build_latest_info{buildName=\"$buildname\"}) by (buildName, buildNumber)",
     "legendFormat": "{{buildName}} {{buildNumber}}"
    }
   ]
  },
  {
   "title": "$buildname",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2.4, "x": 7.199999999999999, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(azure_devops_build_latest_info{result=\"succeeded\", buildName=\"$buildname\"} / azure_devops_build_latest_info{buildName=\"$buildname\"}) by (buildName, buildNumber)",
     "legendFormat": "{{buildName}} {{buildNumber}}"
    }
   ]
  },
  {
   "title": "$buildname",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2.4, "x": 9.6, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(azure_devops_build_latest_info{result=\"succeeded\", buildName=\"$buildname\"} / azure_devops_build_latest_info{buildName=\"$buildname\"}) by (buildName, buildNumber)",
     "legendFormat": "{{buildName}} {{buildNumber}}"
    }
   ]
  },
  {
   "title": "$buildname",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2.4, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(azure_devops_build_latest_info{result=\"succeeded\", buildName=\"$buildname\"} / azure_devops_build_latest_info{buildName=\"$buildname\"}) by (buildName, buildNumber)",
     "legendFormat": "{{buildName}} {{buildNumber}}"
    }
   ]
  },
  {
   "title": "$buildname",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2.4, "x": 14.4, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(azure_devops_build_latest_info{result=\"succeeded\", buildName=\"$buildname\"} / azure_devops_build_latest_info{buildName=\"$buildname\"}) by (buildName, buildNumber)",
     "legendFormat": "{{buildName}} {{buildNumber}}"
    }
   ]
  },
  {
   "title": "$buildname",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2.4, "x": 16.8, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(azure_devops_build_latest_info{result=\"succeeded\", buildName=\"$buildname\"} / azure_devops_build_latest_info{buildName=\"$buildname\"}) by (buildName, buildNumber)",
     "legendFormat": "{{buildName}} {{buildNumber}}"
    }
   ]
  },
  {
   "title": "$buildname",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2.4, "x": 19.2, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(azure_devops_build_latest_info{result=\"succeeded\", buildName=\"$buildname\"} / azure_devops_build_latest_info{buildName=\"$buildname\"}) by (buildName, buildNumber)",
     "legendFormat": "{{buildName}} {{buildNumber}}"
    }
   ]
  },
  {
   "title": "$buildname",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2.4, "x": 21.599999999999998, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(azure_devops_build_latest_info{result=\"succeeded\", buildName=\"$buildname\"} / azure_devops_build_latest_info{buildName=\"$buildname\"}) by (buildName, buildNumber)",
     "legendFormat": "{{buildName}} {{buildNumber}}"
    }
   ]
  },
  {
   "title": "Current Builds",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ceil((rate(azure_devops_stats_agentpool_builds[2m])*100))) by (result)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Network In",
      "dimension": "",
      "dimensionFilter": "*",
      "dimensions": [],
      "metricDefinition": "Microsoft.Compute/virtualMachines",
      "metricName": "Network In Total",
      "resourceGroup": "deployment",
      "resourceName": "deployment-ubuntu",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    },
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Network Out",
      "dimension": "",
      "dimensionFilter": "*",
      "dimensions": [],
      "metricDefinition": "Microsoft.Compute/virtualMachines",
      "metricName": "Network Out Total",
      "resourceGroup": "deployment",
      "resourceName": "deployment-ubuntu",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Build time average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(\n  azure_devops_build_status{type=\"jobDuration\"}\n    + on(buildID) group_left(buildName, result) (0 *azure_devops_build_info{result=\"succeeded\"})\n) by (buildName) > 0",
     "legendFormat": "{{buildName}}"
    }
   ]
  },
  {
   "title": "Build success rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percentunit", "label": "success rate" }
   ],
   "targets": [
    {
     "expr": "count(azure_devops_build_info{result!=\"succeeded\"}) by (buildName) / count(azure_devops_build_info) by (buildName)",
     "legendFormat": "{{ buildName }}"
    }
   ]
  }
 ]
}